environments:
  - name: default
    toolchain:
      os: linux
      arch: amd64
      compiler: go1.18.1
      variant: plain
    warehouse:
      local: /tmp/warehouse
      remote:
        - s3://mirroring-lambda
procedures:
  - name:
    enviroment: default
    source:
      module: codeup.aliyun.com/mirror/admin/admin-api/route
      version: master
    target:
      namespace: admin
      package: route
      version: latest
